# Generated by Django 4.2.18 on 2025-04-03 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_chessmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessmatch',
            name='player_white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
