# Generated by Django 4.2.18 on 2025-04-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessmatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
