# Generated by Django 4.2.18 on 2025-04-05 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_chessmatch_move_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessmatch',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wins',
        ),
        migrations.AddField(
            model_name='chessmatch',
            name='game_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chessmatch',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chessmatch',
            name='last_move_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chessmatch',
            name='turn_color',
            field=models.CharField(default='white', max_length=5),
        ),
        migrations.AddField(
            model_name='chessmatch',
            name='turn_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chessmatch',
            name='winner_color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('draw', 'Draw')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='chessmatch',
            name='winner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
