# Generated by Django 4.2.18 on 2025-04-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_chessmatch_is_active_remove_profile_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessmatch',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
