# Generated by Django 4.2.18 on 2025-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chessmatch_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessmatch',
            name='captured_by_black',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chessmatch',
            name='captured_by_white',
            field=models.JSONField(default=list),
        ),
    ]
