"""added turn_count column to HiScoreChart

Revision ID: c4984e9387a5
Revises: da5b5951c369
Create Date: 2023-08-27 17:32:32.550343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4984e9387a5'
down_revision: Union[str, None] = 'da5b5951c369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hi_score_chart', sa.Column('turn_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hi_score_chart', 'turn_count')
    # ### end Alembic commands ###
